# Generated by Django 3.1.4 on 2021-01-07 12:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_otp_id', models.TextField(blank=True, null=True)),
                ('otp', models.TextField(blank=True, null=True)),
                ('mob_no', models.TextField(blank=True, null=True)),
                ('email_id', models.TextField(blank=True, null=True)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('failure_attempts', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'OTPVerification',
                'verbose_name_plural': 'OTPVerifications',
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referrer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('referrer_mobile', models.CharField(blank=True, max_length=200, null=True)),
                ('referrer_email', models.CharField(blank=True, max_length=100, null=True)),
                ('referee_name', models.CharField(blank=True, max_length=200, null=True)),
                ('referee_mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('referee_email', models.CharField(blank=True, max_length=100, null=True)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Referral',
                'verbose_name_plural': 'Referrals',
            },
        ),
    ]
