# Generated by Django 3.1.4 on 2021-03-23 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0002_auto_20210320_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='referral',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
