# Generated by Django 3.1.4 on 2021-03-23 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0003_auto_20210323_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='referral',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
