# Generated by Django 3.1.3 on 2021-04-29 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0005_gal'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodaysBirthDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=100)),
                ('emp_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Gal',
        ),
    ]
