# Generated by Django 3.1.4 on 2021-04-15 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementPartners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_the_company', models.CharField(max_length=400)),
                ('address_detail', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('name_of_person', models.CharField(max_length=100)),
                ('designation_of_person', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=100)),
                ('type_of_company', models.CharField(max_length=100)),
            ],
        ),
    ]
