# Generated by Django 3.1.4 on 2021-04-15 11:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_placementpartners_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='placementpartners',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placementpartners',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
