# Generated by Django 3.1.4 on 2021-04-15 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210415_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleInterview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isa_academy', models.CharField(max_length=100)),
                ('reason', models.TextField()),
            ],
        ),
    ]
