# Generated by Django 3.1.4 on 2021-04-15 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_treeplantation_treeplantationphotos_watersheddata_watersheddataphotos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treeplantation',
            name='date_of_plantation',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='watersheddata',
            name='date',
            field=models.CharField(max_length=100),
        ),
    ]
