# Generated by Django 3.1.4 on 2021-04-16 08:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210415_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleinterview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
