# Generated by Django 3.1.4 on 2021-04-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_paymentupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentupload',
            name='entries',
            field=models.IntegerField(default=0),
        ),
    ]
