# Generated by Django 3.1.4 on 2021-04-16 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_paymentupload_entries'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsheet',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
