# Generated by Django 3.1.4 on 2021-04-16 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0011_paymentsheet_is_deleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='placementpartners',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.AddField(
            model_name='placementpartners',
            name='address_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='placementpartners',
            name='addressed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='placementpartners',
            name='is_addressed',
            field=models.BooleanField(default=False),
        ),
    ]
