# Generated by Django 3.1.4 on 2021-04-16 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20210416_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequirementPlacementPartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_company', models.CharField(blank=True, max_length=1000, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('course', models.CharField(blank=True, max_length=100, null=True)),
                ('designation', models.CharField(blank=True, max_length=1000, null=True)),
                ('salary', models.CharField(blank=True, max_length=1000, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=1000, null=True)),
                ('job_text', models.CharField(blank=True, max_length=100, null=True)),
                ('job_description_file', models.FileField(blank=True, null=True, upload_to='jobs')),
                ('no_of_opening', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ScheduleInterview',
        ),
    ]
