# Generated by Django 3.1.3 on 2021-04-27 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(blank=True, max_length=100, null=True)),
                ('emp_id', models.CharField(blank=True, max_length=100, null=True)),
                ('batch_start', models.CharField(blank=True, max_length=100, null=True)),
                ('batch_end', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BatchFollowups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainee_id', models.CharField(max_length=100)),
                ('trainee_name', models.CharField(max_length=100)),
                ('application_id', models.CharField(max_length=100)),
                ('batch_id', models.CharField(max_length=100)),
                ('isa_course_id', models.CharField(max_length=100)),
                ('is_follow_up_done', models.BooleanField(default=False)),
                ('follow_up_date_time', models.DateTimeField(blank=True, null=True)),
                ('batch_start_date', models.CharField(blank=True, max_length=100, null=True)),
                ('batch_end_date', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EnrollmentReportStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=1000)),
                ('total_entries', models.IntegerField(default=0)),
                ('total_errors', models.IntegerField(default=0)),
                ('errors_desc', models.TextField(blank=True, default='[]', null=True)),
                ('current_status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Uploaded'), (2, 'Submitted'), (3, 'Fetched Details'), (4, 'Triggered SMS'), (5, 'Completed')], default=0)),
                ('triggered_status', models.BooleanField(default=False)),
                ('is_visible', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialOrganization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('organization_type', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        
        migrations.CreateModel(
            name='IncrementBatchCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('socket_id', models.TextField()),
                ('current_count', models.IntegerField(default=0)),
                ('end_count', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trainee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainee_id', models.CharField(blank=True, max_length=200, null=True)),
                ('applicant_id', models.CharField(blank=True, max_length=200, null=True)),
                ('trainee_name', models.CharField(blank=True, max_length=200, null=True)),
                ('batch_id', models.CharField(blank=True, max_length=100, null=True)),
                ('is_certificate_issued', models.BooleanField(default=False)),
                ('issue_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserBatchFollowups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('completion_date_for_followups', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('assign_to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_to', to=settings.AUTH_USER_MODEL)),
                ('assigned_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_by', to=settings.AUTH_USER_MODEL)),
                ('batch_followups', models.ManyToManyField(to='reports.BatchFollowups')),
            ],
        ),
        migrations.CreateModel(
            name='SourcingReportStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=1000)),
                ('total_entries', models.IntegerField(default=0)),
                ('total_errors', models.IntegerField(default=0)),
                ('errors_desc', models.TextField(blank=True, default='[]', null=True)),
                ('current_status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Uploaded'), (2, 'Submitted'), (3, 'Fetched Details'), (4, 'Triggered SMS'), (5, 'Completed')], default=0)),
                ('triggered_status', models.BooleanField(default=False)),
                ('is_visible', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sourcing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('contact_no', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('centre_name', models.CharField(max_length=100)),
                ('faculty_name', models.CharField(max_length=100)),
                ('sms_status', models.BooleanField(default=False)),
                ('email_status', models.BooleanField(default=False)),
                ('application_id', models.TextField(blank=True, default='[]', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sourcing_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.sourcingreportstatus')),
            ],
        ),
        
        migrations.CreateModel(
            name='FollowUpsReportStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=1000)),
                ('total_entries', models.IntegerField(default=0)),
                ('total_errors', models.IntegerField(default=0)),
                ('errors_desc', models.TextField(blank=True, default='[]', null=True)),
                ('current_status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Uploaded'), (2, 'Submitted'), (3, 'Fetched Details'), (4, 'Triggered SMS'), (5, 'Completed')], default=0)),
                ('triggered_status', models.BooleanField(default=False)),
                ('is_visible', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FollowUps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainee_id', models.CharField(max_length=11)),
                ('centre_name', models.CharField(max_length=100)),
                ('faculty_name', models.CharField(max_length=100)),
                ('contact_no', models.CharField(blank=True, max_length=12, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('sms_status', models.BooleanField(default=False)),
                ('email_status', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('follow_up_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.followupsreportstatus')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_id', models.CharField(blank=True, max_length=12, null=True)),
                ('contact_no', models.CharField(blank=True, max_length=12, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('sms_status', models.BooleanField(default=False)),
                ('email_status', models.BooleanField(default=False)),
                ('trainee_id', models.CharField(blank=True, max_length=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('enrollment_report', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.enrollmentreportstatus')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.CharField(blank=True, max_length=200, null=True)),
                ('is_valid', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('file_path', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trainee_id', models.ForeignKey(blank=True, null=re.RegexFlag['TEMPLATE'], on_delete=django.db.models.deletion.SET_NULL, to='reports.trainee')),
            ],
        ),
        migrations.CreateModel(
            name='BatchFollowUpsRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_of_followups', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('assigned_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_by_user', to=settings.AUTH_USER_MODEL)),
                ('assigned_to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_to_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
