# Generated by Django 3.1.3 on 2021-04-27 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_financialsession_sessionimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialorganization',
            name='name',
            field=models.CharField(blank=True, default='q', max_length=100, null=True),
        ),
    ]
