# Generated by Django 3.1.3 on 2021-04-27 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20210427_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialsession',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.financialorganization'),
        ),
    ]
