# Generated by Django 3.1.3 on 2021-04-27 11:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20210427_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialorganization',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='financialorganization',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
