# Generated by Django 3.1.3 on 2021-04-28 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_certificatetemplates'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatetemplates',
            name='to_show',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='financialorganization',
            name='to_show',
            field=models.BooleanField(default=True),
        ),
    ]
