# Generated by Django 3.1.3 on 2021-04-29 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_auto_20210428_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpactBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiaries', models.CharField(max_length=100)),
                ('total', models.CharField(max_length=100)),
                ('total_males', models.CharField(max_length=100)),
                ('this_month_total', models.CharField(max_length=100)),
                ('males', models.CharField(max_length=100)),
                ('females', models.CharField(max_length=100)),
                ('this_fy_total', models.CharField(max_length=100)),
                ('this_fv_males', models.CharField(max_length=100)),
                ('this_fv_females', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImpactBoxUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.TextField()),
                ('is_imported', models.BooleanField(default=False)),
                ('total_entries', models.IntegerField(default=0)),
                ('errors', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
