# Generated by Django 3.1.3 on 2021-04-29 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_impactbox_impactboxupload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impactbox',
            name='beneficiaries',
        ),
        migrations.RemoveField(
            model_name='impactbox',
            name='females',
        ),
        migrations.RemoveField(
            model_name='impactbox',
            name='males',
        ),
        migrations.RemoveField(
            model_name='impactbox',
            name='this_fv_females',
        ),
        migrations.RemoveField(
            model_name='impactbox',
            name='this_fv_males',
        ),
        migrations.RemoveField(
            model_name='impactbox',
            name='this_fy_total',
        ),
        migrations.RemoveField(
            model_name='impactbox',
            name='this_month_total',
        ),
        migrations.RemoveField(
            model_name='impactbox',
            name='total',
        ),
        migrations.RemoveField(
            model_name='impactbox',
            name='total_males',
        ),
        migrations.AddField(
            model_name='impactbox',
            name='isa_females',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='impactbox',
            name='isa_males',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='impactbox',
            name='isa_this_fv_females',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='impactbox',
            name='isa_this_fv_males',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='impactbox',
            name='isa_this_fy_total',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='impactbox',
            name='isa_this_month_total',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='impactbox',
            name='isa_total',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='impactbox',
            name='isa_total_males',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='impactbox',
            name='rl_females',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='impactbox',
            name='rl_males',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='impactbox',
            name='rl_this_fv_females',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='impactbox',
            name='rl_this_fv_males',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='impactbox',
            name='rl_this_fy_total',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='impactbox',
            name='rl_this_month_total',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='impactbox',
            name='rl_total',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='impactbox',
            name='rl_total_males',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='impactbox',
            name='rseti_females',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='impactbox',
            name='rseti_males',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='impactbox',
            name='rseti_this_fv_females',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='impactbox',
            name='rseti_this_fv_males',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='impactbox',
            name='rseti_this_fy_total',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='impactbox',
            name='rseti_this_month_total',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='impactbox',
            name='rseti_total',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='impactbox',
            name='rseti_total_males',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
