# Generated by Django 3.1.3 on 2021-04-29 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_auto_20210429_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='impactbox',
            name='isa_total_females',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='impactbox',
            name='rl_total_females',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
