# Generated by Django 3.1.3 on 2021-04-29 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_auto_20210429_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='impactbox',
            name='rseti_total_females',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
