# Generated by Django 3.1.3 on 2021-05-03 11:14

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0014_policies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internaljobposting',
            name='job_description',
            field=froala_editor.fields.FroalaField(),
        ),
    ]
