# Generated by Django 3.1.4 on 2021-02-22 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profile'},
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
